### ISSUE TITLE
문서를 한국어로

### ISSUE THREAD

**Issue by chu-tty** [wizard-s/chip8-emulator#3]
# 문서를 한국어로

#2 를 통해 저는 우리 팀이 한글로 작성할 때, 더 정확하고 정교하게 글을 쓸 수 있을 것 같다고 생각했습니다. 따라서 한글로 글을 작성하는 게 맞다고 생각하는데, 어떻게 생각하시나요?

**Comment by Choyeon-17** [comment]
제가 한국어로 번역하겠습니다.
