### ISSUE TITLE
커밋 메시지 규칙 수정

### ISSUE THREAD

**Issue by chu-tty** [wizard-s/chip8-emulator#4]
# 커밋 메시지 규칙 수정

커밋 메시지를 더 일반적이고 덜 형식적으로 만드는 건 어떨까요?

## 표현의 부족함

지금의 타입으로는 당연하지만 모든 변경을 한 커밋 종류로 표현하지 못하고, 추가 단위가 함수가 아닌 경우도 표현하지 못하는 게 단점이라고 생각합니다.

## 지나치게 형식적

형식적인 커밋 메시지는 생기고 사라지는 커밋이 많을 때, 더 쉽게 구분할 수 있는 것이 장점이라고 생각합니다. 그런데 지금 커밋의 수는 적고 (YANGI), 지나치게 형식적이어서 오히려 잘 지켜지지 않는 경우도 있는 것 같습니다. (9cb9f931d2d27f7fb638ab894ab5f313c448ec1d 이 좋은 예시네요.)

## 제안

따라서 지금은 커밋 메시지의 폼을 '명령문 + 관사 사용 안 함'으로 약속하는 게 좋은 것 같습니다.

**Comment by kimsos0723** [comment]
예시좀 알려주시면 이해가 빠를것 같아요

**Comment by kimsos0723** [comment]
예시를 들어주시면 이해가 빠를것 같아요

**Comment by chu-tty** [comment]
예시를 들면 github에서 풀 리퀘스트를 처리하면 생기는 기본 메시지가 좋은 예시인 것 같습니다.

> Merge pull request #N from ...

- 주어 없이 동사 원형으로 `Merge`를 사용했습니다.
- 여기서는 `a/the pull request`가 아닌, `pull request`를 사용했습니다.

**Comment by chu-tty** [comment]
이렇게 작업하기로 정하겠습니다. 아니라면, 다시 이슈를 열어주세요.
