### ISSUE TITLE
유닛 테스팅 도입

### ISSUE THREAD

**Issue by chu-tty** [wizard-s/chip8-emulator#9]
# 유닛 테스팅 도입

계속 cout으로 디버그하고 "C++이여서 힘들다"라고 생각하는 것보다는 지금이라도 유닛 테스팅을 시작해야 한다고 생각합니다.

## 테스트 프레임워크 선택

C++에서 테스트 프레임워크는

- Google Test
- CppUTest
- Catch(2)

정도가 유명한 것 같습니다.

개인적으로는 CppUTest가 학교에서 구할 수 있는 책인 "임베디드 C를 위한 TDD"에서 여러 설명을 해주기 때문에, CppUTest를 추천합니다.

**Comment by kimsos0723** [comment]
CppUTest가 Google test보다 갸벼워?서 좋은것 같아요

**Comment by chu-tty** [comment]
일단 "가볍다"다 무슨 뜻인지 모르겠네요.

아무튼, 지금 보니 설령 한 책에서 CppUTest를 쓰더라도 Google test가 자료의 절대적인 양이 더 많아서, Google test를 쓰는 게 더 좋아 보이네요.

**Comment by kimsos0723** [comment]
솔직히 저는 말할 권한이 없어요
